[project]
name = "fast-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.1",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.46",
]
